# Generated by Django 5.0.6 on 2024-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(help_text='Time limit for the quiz in minutes')),
            ],
        ),
    ]
