# Generated by Django 5.0.7 on 2025-03-19 03:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_users', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter a US phone number', max_length=128, null=True, region='US', unique=True),
        ),
    ]
