# Generated by Django 5.0.7 on 2025-03-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_users', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
